version: '3'

services:

### PHP-FPM Container #######################################

  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ${APPLICATION}:/var/www
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    container_name: 'php-fpm'
    networks:
      - frontend
      - backend

### Networks Setup ############################################

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"
