version: '3'

services:

### PHP-FPM Container #####################################

  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ${APPLICATION}:/var/www
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    networks:
      - frontend
      - backend

### NGINX Server Container ################################

  nginx:
    build:
      context: ./nginx
    volumes:
      - ${APPLICATION}:/var/www
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

### couchdb Container #######################################
  couchdb:
    build:
      context: ./couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - ${DATA_SAVE_PATH}/couchdb/:/opt/couchdb/data
      - ./couchdb/:/usr/local/etc/couchdb/
      - ./logs/couchdb/:/usr/local/var/log/couchdb/
    depends_on:
      - php-fpm
    ports:
      - "5984:5984"
      - "4369:4369"
      - "9100:9100"
    networks:
      - backend

### Networks Setup ########################################

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"
